import type { Metadata } from "next";
import { Toaster } from "@/components/ui/sonner";
import { Geist_Mono } from "next/font/google";
import Providers from "@/components/providers";

import "./globals.css";

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Summarium",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} font-[family-name:var(--font-geist-mono)] antialiased`}
      >
        <Providers>
        {children}
        <Toaster />
        </Providers>
      </body>
    </html>
  );
}
